name: Test SpaceTrack

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Space-Track
        run: |
          curl -c cookies.txt -d "identity=${{ secrets.SPACETRACK_USER }}&password=${{ secrets.SPACETRACK_PASS }}" \
          https://www.space-track.org/ajaxauth/login

      - name: Fetch ISS TLE
        run: |
          curl -b cookies.txt \
          "https://www.space-track.org/basicspacedata/query/class/gp/norad_cat_id/25544/format/tle"
