name: Fetch Space-Track Data

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Space-Track
        run: |
          curl -c cookies.txt -d "identity=${{ secrets.SPACETRACK_USER }}&password=${{ secrets.SPACETRACK_PASS }}" \
          https://www.space-track.org/ajaxauth/login

      - name: Fetch ALL objects (GP JSON)
        run: |
          curl -b cookies.txt \
          "https://www.space-track.org/basicspacedata/query/class/gp/format/json" \
          -o all_objects.json

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: space-track-data
          path: all_objects.json
